### ISSUE TITLE
Add Categories to assessments

### ISSUE THREAD

**Issue by AndreB123** [revaturelabs/1808-cal-v2-meta#100]
# Add Categories to assessments

## Description

add categories to the assessments on the assess batch page

**Comment by AndreB123** [comment]
@Quinn-Donnelly im a little confused on what you are looking for here. The assessments already have categories, and they are displayed once the one of the CORS errors was fixed. 

![image](https://user-images.githubusercontent.com/46233510/62566099-d0684e00-b84d-11e9-970e-06349c42853d.png)

**Comment by Quinn-Donnelly** [comment]
@AndreB123 If they are working now then no challenges. There was a bug report that the categories were not populating. So long as they are being displayed to the user and are stored on the backend then we are good.

**Comment by AndreB123** [comment]
awesome i guess it was just the cors error.
