### ISSUE TITLE
Loading grades for a week

### ISSUE THREAD

**Issue by Quinn-Donnelly** [revaturelabs/1808-cal-v2-meta#17]
ISSUE KEY: [CAL-159]

Load in all grades for each assessment for each associate for each associate. Row for each associate and column for each assessment. Notes should be on the far right column.

[CAL-159]: https://revaturetraining.atlassian.net/browse/CAL-159

**Comment by haandyha** [comment]
To clarify this issue, do you want us to find all grades for each assessment and for each associate only or do you want us to find all grades by the assessment's week number as well?

**Comment by Quinn-Donnelly** [comment]
@haandyha  This will be the loading for a week's grades. So if I am looking at a particular batch week 1 then you would load all the grade for that batch for week 1.

**Comment by Quinn-Donnelly** [comment]
This feature is working but was caused a bug. The bug is documented in #23
