### ISSUE TITLE
Merge Conflicts in QA Service

### ISSUE THREAD

**Issue by Quinn-Donnelly** [revaturelabs/1808-cal-v2-meta#22]
The quality audit service has a merge conflict marker in the pom.xml

[See Merge Conflict Here](https://github.com/revaturelabs/caliber-2-quality-audit-service/blob/dev/pom.xml)

**Comment by Quinn-Donnelly** [comment]
@revaturelabs/1901-jan14-p3 if we could get this resolved quickly as it is currently breaking the builds on dev.

**Comment by peytonshriver** [comment]
I combed through and the merge conflict should be resolved.

**Comment by Quinn-Donnelly** [comment]
@peytonshriver Looks like the merge conflicts have been resolved but there is an unknown type EvaluationService in the NoteService class.

**Comment by peytonshriver** [comment]
Ill investigate, and try to resolve where it is supposed to come from.

**Comment by Quinn-Donnelly** [comment]
@peytonshriver The most recent change introduced to dev seems to have resolved the issue.

**Comment by peytonshriver** [comment]
That should be resolved now. There was a missing import statement.
