### ISSUE TITLE
Fail to get batch overall that does not exist.

### ISSUE THREAD

**Issue by Tkok1996** [revaturelabs/1808-cal-v2-meta#46]
## Description

If you click on a week and a qc overall batch note does not exist in the database for that week/batchId, it will not change the qc overall batch note to match the batchId and week and it will show the qc batch overall note that you were last on. How to recreate this bug - Year 2019, Q1, Dan Pickles, select week 3 and in console it will state " XHR failed loading: GET "http://localhost:10000/qa/audit/notes/overall/2/3" ".

**Comment by JonathanMcG** [comment]
Bug is unreplicatable, marking as closed
