### ISSUE TITLE
Filter Batches by year and quarter

### ISSUE THREAD

**Issue by Quinn-Donnelly** [revaturelabs/1808-cal-v2-meta#9]
ISSUE KEY: [CAL-152]

As a user I can filter through batches I have access to by year and by quarter.

User should be able to select a batch within the specified criteria (if any time in that batch overlaps selected timeframe) and have the most recent week should be displayed initially.

[CAL-152]: https://revaturetraining.atlassian.net/browse/CAL-152

**Comment by magikarpp** [comment]
What does it mean for a user to have access to a batch? Would that refer to the Trainer and Co-Trainer of each batch?

**Comment by Quinn-Donnelly** [comment]
There are a few roles in the system yes the co trainer and trainer should have access as well as the higher roles. For now the auth is not implemented so just worry about trainer and co trainer the auth is not a requirement.

**Comment by Quinn-Donnelly** [comment]
This was resolved in Spring 559.
